### ISSUE TITLE
Create dedicated DB for prod and staging

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/smb-portal#106]
Created a DB for the staging and prod smb-portal instances, on the same RDS instance.

**Comment by ricardogsilva** [comment]
Created two DBs (now I'm thinking this might not be what you wanted) and hooked them up to `staging` and `goodgo` instances:

**Comment by ricardogsilva** [comment]
Created two DBs (now I'm thinking this might not be what you wanted) and hooked them up to `staging` and `goodgo` instances:
