### ISSUE TITLE
Provisioning and deployment of Dev server

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/smb-portal#117]
The following instances must be setup on the EC2 Dev instance:

- smb-portal dev branch
- Keycloak

EC2 Dev address and credentials are available in the docs.

**Comment by ricardogsilva** [comment]
- [x] keycloak (using H2 DB)
- [x] smb-portal code (dev branch)
- [x] portal code runs through uwsgi
- [x] nginx does reverse proxying for portal (with TLS)
- [x] nginx does reverse proxying for keycloak (with TLS)
- [ ] DNS entry for dev.savemybike.geo-solutions.it pointing to the EC2 dev instance
- [ ] Update internal docs

I believe I've set most things up, with the most notable exception being the DNS update. I'm not sure if I'm the one to do the DNS management. If so, I'll need some more info/credentials.

I'm also in the process of updating the internal docs. However, I need to verify everything is working before considering them updated (some things might need to be adjusted)

When the DNS is updated I'll be able to test if everything is working as expected and finish the docs.

**Comment by giohappy** [comment]
Alessandro will do it. Ask him tomorrow morning
