### ISSUE TITLE
Portal site map

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/smb-portal#12]
Define a well defined hierarchical structures for sections and functional areas (site map) using Django urls / views.
This will help the user navigating through the contents and forms, with the help of  **breadcrumbs**.

The structure will be defined [in this doc](https://docs.google.com/document/d/1fkMW9_higjE2UeakkpHvMiD3-zpa-b3mh5AGxEftg8s).

NOTE: In case it helps we can use https://django-bootstrap-breadcrumbs.readthedocs.io/en/latest/

**Comment by ricardogsilva** [comment]
The portal is already using breadcrumbs, so I think we should close this
