### ISSUE TITLE
GetDomainValues endpoint for Geoserver's multidim extension

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/smb-portal#122]
This proposal is for the creation of a new **GetDomainValues** endpoint to the [WMTS MultiDimensional extension](http://docs.opengeospatial.org/per/16-042r1.html).

The goal is to let a client request **a (paged) list of sorted unique domain values lower / greater then a certain value**.

### Description

The request params mimic [those implemented by the DescribeDomain endpoint](http://docs.geoserver.org/latest/en/user/community/wmts-multidimensional/index.html#describedomains). This will simplify the development and gives consistency to the API.
The following request parameters should be implemented:

- **Service**=WMTS
- **Request**=GetDomainValues
- **Version**=1.0.0
- **Layer**: the (multi) dimensional layer we're asking the domain values
bbox=minx,miny,maxx,maxy
- **DimensionIdentifier**= At most one per dimension, a range described as min/max, restricting the domain of this dimension. The range can be lower bounded ("min/"), upper bounded ("/max") or double bounded ("min/max")
- **Domain**= name of the LAYER's dimension we're querying
- **Limit**= number of unique values we want to obtain, capped by a fixed limit configured server side (max_page_values). I.e. the number of returned values will be **min(LIMIT,max_page_values)**

### Sample requests

- http://server.com/ows?Service=WMTS&Request=GetDomainValues&Layer=<layername>&domain=time&time=2017-08-01T00:00:00.000/&Limit=20
  
  will return the next 20 (or max_page_values) unique time values since 2017-08-01T00:00:00.000

- http://server.com/ows?Service=WMTS&Request=GetDomainValues&Layer=<layername>&domain=time&time=/2017-08-01T00:00:00.000&Limit=20&Offset=20
  
  will return the previous 20 (or max_page_values) values, before the first 20, since 2017-08-01T00:00:00.000

- http://server.com/ows?Service=WMTS&Request=GetDomainValues&Layer=<layername>&domain=time&time=2017-08-01T00:00:00.000/&elev=50/100&Limit=20
  
  will return the next 20 values from the features having the elevation dimension between 50 and 100

**Comment by aaime** [comment]
Agree with the proposal and we have an estimate, ready to work on it as soon as it gets prioritized (it's top of my ready column now, but not sure if it happened only because it's the last being created, or it was moved there on purpose)

**Comment by simboss** [comment]
@aaime remember to update the documentation in the GeoServer docs.

**Comment by aaime** [comment]
Is the direction gone? direction=up/down

**Comment by aaime** [comment]
Ah, we don't really need it because the domain filter directions tells us where to go

**Comment by aaime** [comment]
Ouff... turns out I cannot use open intervals (min/ or /max), as intervals are used in other parts of the protocol and are always inclusive of their extrema, while here we need to filter so that the extrema is excluded. The code building the intervals and filters is shared, and besides the syntax is the same as DescribeDomain, so it would be odd to have same syntax and different semantic.

Ooooh well... I guess I'll have to go back to using reference=value and direction=up/down.
I hope this is not too much of an inconvenience client side?

**Comment by aaime** [comment]
After some discussion with Lorenzo, we'll do this:
* Interval filtering is back to min/max, can be used for any dimension, always includes the extrema of the internal like in DescribeDomain
* Nuovi parametri:
  - startValue = value -> il valore di riferimento (può mancare, viene usato il valore più piccolo o più grande in funzione del sort)
  - sort = asc/desc -> la direzione di ordinamento dati (default asc)

**Comment by aaime** [comment]
Sorry! :-p

**Comment by aaime** [comment]
So the code has been  merged, docs here:
http://docs.geoserver.org/latest/en/user/community/wmts-multidimensional/index.html#getdomainvalues

Should be on cloudsdi today (midday deploy hopefully). I did not build a UI to configure the max server side "limit" value yet, keeping some time aside for bug fixing and other feedback. If we get some left at the end adding the UI should be quick.
