### ISSUE TITLE
Repurpose region of interest to only be used for calculating competition scores

### ISSUE THREAD

**Issue by ricardogsilva** [geosolutions-it/smb-portal#196]
Currently track ingestion is restricted to points that fall within the bounds of `tracks.models.RegionOfInterest` records.

Lets change that so that tracks and segments will be generated from all valid collected points, regardless of the underlying points intersecting any region of interest.

#### Note
The `RegionOfInterest` model is not to be removed as of now - it will be repurposed to serve as an optional restriction for competitions (in a subsequent issue)

**Comment by ricardogsilva** [comment]
This replaces geosolutions-it/smb-portal#196 since the work to be done is effectively on this repo

**Comment by ricardogsilva** [comment]
This is superseeded by geosolutions-it/smb-backend#53

**Comment by giohappy** [comment]
closing in favour of https://github.com/geosolutions-it/smb-backend/issues/53
