### ISSUE TITLE
spatial-ref-sys is managed by PostGIS extension

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/smb-portal#4]
This isn't required: https://github.com/geosolutions-it/smb-portal/blob/dev/registration/models.py#L68
spatial-ref-sys is a table that is created and managed by PostGIS extension. 
See: https://postgis.net/docs/using_postgis_dbmanagement.html#spatial_ref_sys

**Comment by DarnelleF** [comment]
it isn't managed but will be deleted

**Comment by giohappy** [comment]
???
The migration process doesn't delete pre existing tables.

2018-05-21 16:49 GMT+02:00 Darnelle Fevrier <notifications@github.com>:

**Comment by DarnelleF** [comment]
it wasnt migrated because the managed attribute was set to false

**Comment by giohappy** [comment]
That table is created by PostGIS.

You have it remove it from the models. It's something that Django doesn't have to care of.

**Comment by DarnelleF** [comment]
i did

**Comment by giohappy** [comment]
assign the In Test label when you think they're ready to be closed.
