### ISSUE TITLE
Add django-crispy-forms to requirements

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/smb-portal#48]

**Comment by ricardogsilva** [comment]
It is already there:

https://github.com/geosolutions-it/smb-portal/blob/dev/requirements/production.txt#L6

**Comment by giohappy** [comment]
Sorry, I was lookint to master :(

**Comment by ricardogsilva** [comment]
That happens to me 5 times a day too :smile_cat: 

Perhaps you could change the repo's default branch to `dev`?
