### ISSUE TITLE
PEP8 coding guidelines

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/smb-portal#7]
Code should follow PEP8 guidelines, at leasr for:

Please verify the current coding styles:

 - [Blank lines](https://www.python.org/dev/peps/pep-0008/#blank-lines)
 - [Maximum line lenght](https://www.python.org/dev/peps/pep-0008/#maximum-line-length)

**Comment by ricardogsilva** [comment]
Most of the code is now in good shape regarding PEP8 guidelines. django is now the main culprit for most errors, since its autogenerated migrations files are usually above 79 characters in length.

**Comment by giohappy** [comment]
that's ok. we don't care for migrations...
