### ISSUE TITLE
Change BikeObservation reporter to text field

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/smb-portal#73]
To simplify management the reporter field must be changed to text field (instead of User). The external system will be able to submit observations from new sources without having to add each source "reporter" to the portal DB.

We should have three fields:
 - reporter_id
 - reporter_type
 - reporter_name

that will be filled by the external system

**Comment by ricardogsilva** [comment]
1. Should we assume any specific rule for the `reporter_id`? I'm making it a `CharField` with a `max_lenght=50`
2. Should we provide some fixed choices for the `reporter_type` field? If so, which ones? Also, should this value allow blank entries? I'm assuming it should be mandatory
3. Should the `reporter_name` be mandatory? I'm assuming yes
