### ISSUE TITLE
Describe Django project setup inside README

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/smb-portal#8]
We need to describe the steps to setup the environment and run the Django application.

 - setup virtualenv for Django and the application requirements
 - configure the settings 
 - run management commands to:
    - migrate
    - run the Django dev server

for the virtualenv requirements see #3

**Comment by giohappy** [comment]
@DarnelleF I've included the "local_settings" pattern [here ](https://github.com/geosolutions-it/smb-portal/blob/dev/smbportal/settings.py#L164) to let the user define its own DB.
These should be described in the README.

**Comment by DarnelleF** [comment]
ok i will

On Thu, May 24, 2018 at 10:31 AM, Giovanni Allegri <notifications@github.com
